name: Run Market Report Script

on:
  schedule:
    - cron: '0 3,15 * * *'  # Runs at 5 AM & 5 PM SAST (UTC+2 converted to UTC)
  workflow_dispatch:  # Allows manual trigger

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pycoingecko matplotlib pandas seaborn pillow

      - name: Run Market Report Script
        run: |
          echo "🚀 Running Market Report Script..."
          python market_report.py

      - name: Check If Infographic Exists
        run: |
          if [ ! -f "financial_infographic.png" ]; then
            echo "❌ ERROR: Infographic was not generated!"
            exit 1
          fi
          echo "✅ Infographic successfully created."

      - name: Upload Infographic as an Artifact
        uses: actions/upload-artifact@v4
        with:
          name: financial-infographic
          path: financial_infographic.png
          retention-days: 7  # Keep the file for 7 days
