name: Run Market Report Script

on:
  schedule:
    - cron: "0 3,15 * * *"  # Runs at 3 AM & 3 PM UTC (which is 5 AM & 5 PM SAST)
  workflow_dispatch:  # Allows manual triggering

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install yfinance pycoingecko matplotlib pandas seaborn pillow

      - name: Run Script
        run: python market_report.py
