name: Run Market Report Script

on:
  schedule:
    - cron: '0 3,15 * * *'  # Runs at 5 AM & 5 PM SAST (Convert to UTC)
  workflow_dispatch:  # Allows manual trigger

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Debug Environment Variables
        run: |
          echo "🔍 EMAIL_PASSWORD: ${EMAIL_PASSWORD:+SET}"
        env:
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

      - name: Run Market Report Script
        run: python market_report.py
        env:
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
