name: Run Market Report Script Please

on:
  schedule:
    - cron: '0 3,15 * * *'  # Runs at 5 AM & 5 PM SAST (Convert to UTC)

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Debug Secrets
        run: echo "EMAIL_PASSWORD is set"
        env:
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

      - name: Run Market Report Script
        run: python market_report.py
        env:
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
